CREATE OR REPLACE PROCEDURE SAMPLE_NATION()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    CREATE OR REPLACE TABLE STAGE_NATION(
         N_NATIONKEY	NUMBER(38,0)
        ,N_NAME	VARCHAR(25)
        ,N_REGIONKEY	NUMBER(38,0)
        ,N_COMMENT	VARCHAR(152)
        ,GMT_TIMESTAMP TIMESTAMP
        );
    TRUNCATE TABLE STAGE_NATION;
    INSERT INTO STAGE_NATION 
            SELECT N_NATIONKEY
		,N_NAME
		,N_REGIONKEY
		,N_COMMENT
		,CURRENT_TIMESTAMP AS GMT_TIMESTAMP FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
    RETURN 'NATION DATA COPIED INTO OUR DB';
END;

