CREATE OR REPLACE PROCEDURE SAMPLE_NATION()
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    INSERT INTO STAGE_NATION 
            SELECT N_NATIONKEY
		,N_NAME
		,N_REGIONKEY
		,N_COMMENT
		,CURRENT_TIMESTAMP AS GMT_TIMESTAMP FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
    RETURN 'NATION DATA COPIED INTO OUR DB';
END;

