dbt_project: Run Sample Nation
  target: prod
  outputs:
    prod:
      type: snowflake
      account: AXYLLYI-BC38465.snowflakecomputing.com
      user: demosf
      password: "{{ env_var('Venu@123456789') }}"
      role: accountadmin
      database: DEMO_DBT
      warehouse: DBT_WH
      schema: DEMO_DBT_SCHEMA
      threads: 4
